### ISSUE TITLE
Clean UP & Dockerization eos77w8

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos77w8#4]

**Comment by GemmaTuron** [comment]
@emmakodes 
The model test failed, please check

**Comment by emmakodes** [comment]
Hello @GemmaTuron `test-model.yml` workflow stopped at the step of installing ersilia. First with the following error: 
```
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
Running setup.py clean for ersilia
╰─> [830 lines of output]
```
Not sure, why it should complain about the `setup.py` file of ersilia since there are no new changes to ersilia codebase lately. I checked `Install dependencies` step which is the step before `Install ersilia` and I discover that `openssl-1.1.1u` is not installed.` openssl-1.1.1u`  is usually installed by other models during workflow runs as one of the dependencies for ersilia but somehow this model workflow never installed it.

My thoughts are we re-run the workflow since there are no new changes to ersilia codebase lately. Also, I have posted a message on Slack to get others input.

**Comment by GemmaTuron** [comment]
thanks @emmakodes 
IT was an airtable outage. I'll re run the workflows

**Comment by GemmaTuron** [comment]
@emmakodes 
Do you think the ersilia.json is needed for anything? because it might be confusing to have another json file there

**Comment by GemmaTuron** [comment]
@emmakodes 

Please see my comment above

**Comment by emmakodes** [comment]
Hello @GemmaTuron I checked and I discovered the model works without `ersilia.json` file. I have opened a PR with `ersilia.json` deleted.
